server:
  port: 9000

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://twhuang.top:3306/breakblog?&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: breakblog
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: BreakBlogHikariCP
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  redis:
    host: twhuang.top
    password: breakblog
    port: 6379
    database: 0
    timeout: 5000
    lettuce:
      pool:
        min-idle: 1
        max-idle: 5
        max-wait: -1
        max-active: 10
  servlet:
    multipart:
      #开启文件上传
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  mapper-locations: classpath*:top/twhuang/mapper/xml/*Mapper.xml
  type-aliases-package: top.twhuang.entity
  global-config:
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

breakblog:
  upload:
    type: local
    path: /usr/local/nginx/html/file
    host: https://twhuang.top/file