server:
  port: 9000

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: breakblog
    url: jdbc:mysql://106.53.155.82:3306/breakblog-sb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    platform: mysql
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
  redis:
    host: 106.53.155.82
    password: breakblog
    port: 6379
    jedis:
      pool:
        max-active: 10
        min-idle: 0
        max-idle: 10
        max-wait: -1
    database: 0
    timeout: 3000
  thymeleaf:
    cache: false
    encoding: utf-8
    servlet:
      content-type: text/html
  servlet:
    multipart:
      #开启文件上传
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  mapper-locations: classpath*:me/breakblog/mapper/xml/*Mapper.xml
  type-aliases-package: me.breakblog.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

app:
  upload:
    type: local
    path: /usr/local/nginx/html/file
    host: http://www.twhuang.me:9010