spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "080155"
    url: jdbc:mysql://localhost:3306/breakblog-sb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  mapper-locations: classpath*:me/breakblog/mapper/xml/*Mapper.xml
  type-aliases-package: me.breakblog.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl