server:
  port: 9001

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: bigsight2019
    url: jdbc:mysql://192.168.2.220:3306/breakblog-sb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    platform: mysql
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
  redis:
    host: 192.168.2.220
    password: bigsight2019
    port: 6379
    jedis:
      pool:
        max-active: 10
        min-idle: 0
        max-idle: 10
        max-wait: -1
    database: 0
    timeout: 3000

  thymeleaf:
    cache: false
    encoding: utf-8
    servlet:
      content-type: text/html

mybatis-plus:
  mapper-locations: classpath*:me/breakblog/mapper/xml/*Mapper.xml
  type-aliases-package: me.breakblog.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

